#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 85
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["HelloApp2/HelloApp2/HelloApp2.csproj", "HelloApp2/HelloApp2/"]
RUN dotnet restore "HelloApp2/HelloApp2/HelloApp2.csproj"
COPY . .
WORKDIR "/src/HelloApp2/HelloApp2"
RUN dotnet build "HelloApp2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HelloApp2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HelloApp2.dll"]